import { MacModel, ChipFamily, DeviceType } from './types';

export const siliconData: MacModel[] = [
  // ==========================================
  // M4 Series (2024)
  // ==========================================
  {
    id: 'm4-max-16-16-40',
    name: 'MacBook Pro 16" (Late 2024)',
    type: DeviceType.Laptop,
    chip: 'M4 Max',
    family: ChipFamily.M4,
    cores_cpu: '16 (12P+4E)',
    cores_gpu: 40,
    memory: '48GB - 128GB',
    releaseYear: 2024,
    singleCoreScore: 4060,
    multiCoreScore: 26800,
    metalScore: 192000,
    basePriceUSD: 3999,
    description: 'The absolute pinnacle of mobile computing. Destroys desktop workstations in 3D rendering and LLM training tasks.'
  },
  {
    id: 'm4-max-14-14-32',
    name: 'MacBook Pro 14" (Late 2024)',
    type: DeviceType.Laptop,
    chip: 'M4 Max',
    family: ChipFamily.M4,
    cores_cpu: '14 (10P+4E)',
    cores_gpu: 32,
    memory: '36GB - 96GB',
    releaseYear: 2024,
    singleCoreScore: 4000,
    multiCoreScore: 24500,
    metalScore: 155000,
    basePriceUSD: 3199,
    description: 'Portable powerhouse. The 14-inch form factor with Max chip is the densest performance-per-inch laptop available.'
  },
  {
    id: 'm4-pro-16-14-20',
    name: 'MacBook Pro 16" (Late 2024)',
    type: DeviceType.Laptop,
    chip: 'M4 Pro',
    family: ChipFamily.M4,
    cores_cpu: '14 (10P+4E)',
    cores_gpu: 20,
    memory: '24GB - 48GB',
    releaseYear: 2024,
    singleCoreScore: 3950,
    multiCoreScore: 22800,
    metalScore: 112000,
    basePriceUSD: 2499,
    description: 'The sweet spot for high-end creative pros. Incredible battery life with near-Max CPU performance.'
  },
  {
    id: 'm4-pro-14-12-16',
    name: 'MacBook Pro 14" (Late 2024)',
    type: DeviceType.Laptop,
    chip: 'M4 Pro',
    family: ChipFamily.M4,
    cores_cpu: '12 (8P+4E)',
    cores_gpu: 16,
    memory: '24GB - 48GB',
    releaseYear: 2024,
    singleCoreScore: 3920,
    multiCoreScore: 22000,
    metalScore: 105000,
    basePriceUSD: 1999,
    description: 'Replaces the previous entry-level Pro with significantly higher bandwidth and ray-tracing capabilities.'
  },
  {
    id: 'm4-mbp-14-base',
    name: 'MacBook Pro 14" (Late 2024)',
    type: DeviceType.Laptop,
    chip: 'M4',
    family: ChipFamily.M4,
    cores_cpu: '10 (4P+6E)',
    cores_gpu: 10,
    memory: '16GB - 32GB',
    releaseYear: 2024,
    singleCoreScore: 3850,
    multiCoreScore: 15200,
    metalScore: 57500,
    basePriceUSD: 1599,
    description: 'The best value MacBook Pro. Now starts with 16GB RAM and supports dual external displays (lid open).'
  },
  {
    id: 'm4-imac',
    name: 'iMac 24" (2024)',
    type: DeviceType.Desktop,
    chip: 'M4',
    family: ChipFamily.M4,
    cores_cpu: '10 (4P+6E)',
    cores_gpu: 10,
    memory: '16GB - 32GB',
    releaseYear: 2024,
    singleCoreScore: 3800,
    multiCoreScore: 15000,
    metalScore: 58000,
    basePriceUSD: 1299,
    description: 'The definitive all-in-one. M4 makes it surprisingly capable for video editing and light gaming.'
  },
  {
    id: 'm4-mini-pro',
    name: 'Mac Mini Pro (2024)',
    type: DeviceType.Desktop,
    chip: 'M4 Pro',
    family: ChipFamily.M4,
    cores_cpu: '12 (8P+4E)',
    cores_gpu: 16,
    memory: '24GB - 64GB',
    releaseYear: 2024,
    singleCoreScore: 3900,
    multiCoreScore: 22000,
    metalScore: 105000,
    basePriceUSD: 1399,
    description: 'A tiny cube with workstation power. The best value-for-performance desktop on the market.'
  },
  {
    id: 'm4-mini',
    name: 'Mac Mini (2024)',
    type: DeviceType.Desktop,
    chip: 'M4',
    family: ChipFamily.M4,
    cores_cpu: '10 (4P+6E)',
    cores_gpu: 10,
    memory: '16GB - 32GB',
    releaseYear: 2024,
    singleCoreScore: 3800,
    multiCoreScore: 15000,
    metalScore: 58000,
    basePriceUSD: 599,
    description: 'Smaller footprint, massive power jump. The entry-level king.'
  },
  {
    id: 'ipad-pro-m4-13',
    name: 'iPad Pro 13" (M4)',
    type: DeviceType.Tablet,
    chip: 'M4',
    family: ChipFamily.M4,
    cores_cpu: '10 (4P+6E)',
    cores_gpu: 10,
    memory: '8GB - 16GB',
    releaseYear: 2024,
    singleCoreScore: 3700,
    multiCoreScore: 14500,
    metalScore: 53000,
    basePriceUSD: 1299,
    description: 'The thinnest Apple product ever. M4 brings massive neural engine improvements for AI tasks on the go.'
  },

  // ==========================================
  // M3 Series (2023-2024)
  // ==========================================
  {
    id: 'm3-max-16-40',
    name: 'MacBook Pro 16" (Late 2023)',
    type: DeviceType.Laptop,
    chip: 'M3 Max',
    family: ChipFamily.M3,
    cores_cpu: '16 (12P+4E)',
    cores_gpu: 40,
    memory: '48GB - 128GB',
    releaseYear: 2023,
    singleCoreScore: 3200,
    multiCoreScore: 21500,
    metalScore: 156000,
    basePriceUSD: 3999,
    description: 'Introduced Hardware Ray Tracing. A monster for 3D work.'
  },
  {
    id: 'm3-max-14-30',
    name: 'MacBook Pro 14" (Late 2023)',
    type: DeviceType.Laptop,
    chip: 'M3 Max',
    family: ChipFamily.M3,
    cores_cpu: '14 (10P+4E)',
    cores_gpu: 30,
    memory: '36GB - 96GB',
    releaseYear: 2023,
    singleCoreScore: 3150,
    multiCoreScore: 19500,
    metalScore: 128000,
    basePriceUSD: 3199,
    description: 'Extreme power density.'
  },
  {
    id: 'm3-pro-12-18',
    name: 'MacBook Pro 14"/16" (Late 2023)',
    type: DeviceType.Laptop,
    chip: 'M3 Pro',
    family: ChipFamily.M3,
    cores_cpu: '12 (6P+6E)',
    cores_gpu: 18,
    memory: '18GB - 36GB',
    releaseYear: 2023,
    singleCoreScore: 3100,
    multiCoreScore: 15500,
    metalScore: 78000,
    basePriceUSD: 1999,
    description: 'Efficient and powerful, though slightly less memory bandwidth than its predecessor.'
  },
  {
    id: 'm3-mbp-14-base',
    name: 'MacBook Pro 14" (Late 2023)',
    type: DeviceType.Laptop,
    chip: 'M3',
    family: ChipFamily.M3,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 10,
    memory: '8GB - 24GB',
    releaseYear: 2023,
    singleCoreScore: 3080,
    multiCoreScore: 11900,
    metalScore: 48000,
    basePriceUSD: 1599,
    description: 'Replaced the 13" MacBook Pro. Great screen, but base model had 8GB RAM.'
  },
  {
    id: 'm3-imac',
    name: 'iMac 24" (2023)',
    type: DeviceType.Desktop,
    chip: 'M3',
    family: ChipFamily.M3,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 10,
    memory: '8GB - 24GB',
    releaseYear: 2023,
    singleCoreScore: 3050,
    multiCoreScore: 11800,
    metalScore: 48000,
    basePriceUSD: 1299,
    description: 'A colorful all-in-one update.'
  },
  {
    id: 'm3-air-13',
    name: 'MacBook Air 13"/15" (2024)',
    type: DeviceType.Laptop,
    chip: 'M3',
    family: ChipFamily.M3,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 10,
    memory: '8GB - 24GB',
    releaseYear: 2024,
    singleCoreScore: 3050,
    multiCoreScore: 11800,
    metalScore: 47500,
    basePriceUSD: 1099,
    description: 'The standard for consumer laptops. Supports two external displays with lid closed.'
  },

  // ==========================================
  // M2 Series (2022-2023)
  // ==========================================
  {
    id: 'm2-ultra-macpro',
    name: 'Mac Pro (2023)',
    type: DeviceType.Desktop,
    chip: 'M2 Ultra',
    family: ChipFamily.M2,
    cores_cpu: '24 (16P+8E)',
    cores_gpu: 76,
    memory: '64GB - 192GB',
    releaseYear: 2023,
    singleCoreScore: 2850,
    multiCoreScore: 21800,
    metalScore: 225000,
    basePriceUSD: 6999,
    description: 'The return of PCIe expansion, but limited by Apple Silicon architecture (no dGPU support).'
  },
  {
    id: 'm2-ultra-studio',
    name: 'Mac Studio (2023)',
    type: DeviceType.Desktop,
    chip: 'M2 Ultra',
    family: ChipFamily.M2,
    cores_cpu: '24 (16P+8E)',
    cores_gpu: 76,
    memory: '64GB - 192GB',
    releaseYear: 2023,
    singleCoreScore: 2800,
    multiCoreScore: 21500,
    metalScore: 220000,
    basePriceUSD: 3999,
    description: 'Same power as the Mac Pro for $3000 less. The ultimate compact workstation.'
  },
  {
    id: 'm2-max-studio',
    name: 'Mac Studio (2023)',
    type: DeviceType.Desktop,
    chip: 'M2 Max',
    family: ChipFamily.M2,
    cores_cpu: '12 (8P+4E)',
    cores_gpu: 38,
    memory: '32GB - 96GB',
    releaseYear: 2023,
    singleCoreScore: 2780,
    multiCoreScore: 15000,
    metalScore: 136000,
    basePriceUSD: 1999,
    description: 'Excellent value for video editors who don\'t need Ultra power.'
  },
  {
    id: 'm2-max-16-38',
    name: 'MacBook Pro 16" (Early 2023)',
    type: DeviceType.Laptop,
    chip: 'M2 Max',
    family: ChipFamily.M2,
    cores_cpu: '12 (8P+4E)',
    cores_gpu: 38,
    memory: '32GB - 96GB',
    releaseYear: 2023,
    singleCoreScore: 2750,
    multiCoreScore: 14800,
    metalScore: 135000,
    basePriceUSD: 3499,
    description: 'HDMI 2.1 support and WiFi 6E arrived with this generation.'
  },
  {
    id: 'm2-pro-14',
    name: 'MacBook Pro 14" (Early 2023)',
    type: DeviceType.Laptop,
    chip: 'M2 Pro',
    family: ChipFamily.M2,
    cores_cpu: '12 (8P+4E)',
    cores_gpu: 19,
    memory: '16GB - 32GB',
    releaseYear: 2023,
    singleCoreScore: 2650,
    multiCoreScore: 14200,
    metalScore: 52000,
    basePriceUSD: 1999,
    description: 'A solid iterative update over the M1 Pro.'
  },
  {
    id: 'm2-pro-mini',
    name: 'Mac Mini (2023)',
    type: DeviceType.Desktop,
    chip: 'M2 Pro',
    family: ChipFamily.M2,
    cores_cpu: '12 (8P+4E)',
    cores_gpu: 19,
    memory: '16GB - 32GB',
    releaseYear: 2023,
    singleCoreScore: 2650,
    multiCoreScore: 14200,
    metalScore: 52000,
    basePriceUSD: 1299,
    description: 'The first time a "Pro" chip came to the Mac Mini.'
  },
  {
    id: 'm2-mini',
    name: 'Mac Mini (2023)',
    type: DeviceType.Desktop,
    chip: 'M2',
    family: ChipFamily.M2,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 10,
    memory: '8GB - 24GB',
    releaseYear: 2023,
    singleCoreScore: 2600,
    multiCoreScore: 9800,
    metalScore: 45000,
    basePriceUSD: 599,
    description: 'Price drop to $599 made this an instant recommendation.'
  },
  {
    id: 'm2-air-15',
    name: 'MacBook Air 15" (2023)',
    type: DeviceType.Laptop,
    chip: 'M2',
    family: ChipFamily.M2,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 10,
    memory: '8GB - 24GB',
    releaseYear: 2023,
    singleCoreScore: 2600,
    multiCoreScore: 10000,
    metalScore: 45000,
    basePriceUSD: 1299,
    description: 'The first 15-inch Air. Perfect for non-pro users needing screen real estate.'
  },
  {
    id: 'm2-air-13',
    name: 'MacBook Air 13" (2022)',
    type: DeviceType.Laptop,
    chip: 'M2',
    family: ChipFamily.M2,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 8,
    memory: '8GB - 24GB',
    releaseYear: 2022,
    singleCoreScore: 2580,
    multiCoreScore: 9700,
    metalScore: 40000,
    basePriceUSD: 1199,
    description: 'Redesigned chassis, MagSafe returns, Midnight color.'
  },
  {
    id: 'm2-mbp-13',
    name: 'MacBook Pro 13" (2022)',
    type: DeviceType.Laptop,
    chip: 'M2',
    family: ChipFamily.M2,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 10,
    memory: '8GB - 24GB',
    releaseYear: 2022,
    singleCoreScore: 2580,
    multiCoreScore: 9800,
    metalScore: 45000,
    basePriceUSD: 1299,
    description: 'The last Touch Bar Mac. An odd duck in the lineup.'
  },
  {
    id: 'ipad-pro-m2-12',
    name: 'iPad Pro 12.9" (M2)',
    type: DeviceType.Tablet,
    chip: 'M2',
    family: ChipFamily.M2,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 10,
    memory: '8GB - 16GB',
    releaseYear: 2022,
    singleCoreScore: 2600,
    multiCoreScore: 9700,
    metalScore: 46000,
    basePriceUSD: 1099,
    description: 'Hover pencil support and ProRes video capture.'
  },
  {
    id: 'ipad-air-m2-13',
    name: 'iPad Air 13" (M2)',
    type: DeviceType.Tablet,
    chip: 'M2',
    family: ChipFamily.M2,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 9,
    memory: '8GB',
    releaseYear: 2024,
    singleCoreScore: 2590,
    multiCoreScore: 9600,
    metalScore: 42000,
    basePriceUSD: 799,
    description: 'The first large-screen iPad Air. Brings M2 performance to a more affordable price point.'
  },

  // ==========================================
  // M1 Series (2020-2022)
  // ==========================================
  {
    id: 'm1-ultra-studio',
    name: 'Mac Studio (2022)',
    type: DeviceType.Desktop,
    chip: 'M1 Ultra',
    family: ChipFamily.M1,
    cores_cpu: '20 (16P+4E)',
    cores_gpu: 64,
    memory: '64GB - 128GB',
    releaseYear: 2022,
    singleCoreScore: 2400,
    multiCoreScore: 17500,
    metalScore: 150000,
    basePriceUSD: 3999,
    description: 'Two M1 Max chips fused together using UltraFusion.'
  },
  {
    id: 'm1-max-studio',
    name: 'Mac Studio (2022)',
    type: DeviceType.Desktop,
    chip: 'M1 Max',
    family: ChipFamily.M1,
    cores_cpu: '10 (8P+2E)',
    cores_gpu: 32,
    memory: '32GB - 64GB',
    releaseYear: 2022,
    singleCoreScore: 2390,
    multiCoreScore: 12600,
    metalScore: 110000,
    basePriceUSD: 1999,
    description: 'Introduced the Studio form factor.'
  },
  {
    id: 'm1-max-16-32',
    name: 'MacBook Pro 16" (2021)',
    type: DeviceType.Laptop,
    chip: 'M1 Max',
    family: ChipFamily.M1,
    cores_cpu: '10 (8P+2E)',
    cores_gpu: 32,
    memory: '32GB - 64GB',
    releaseYear: 2021,
    singleCoreScore: 2380,
    multiCoreScore: 12500,
    metalScore: 110000,
    basePriceUSD: 3499,
    description: 'XDR Display, ports returned. A massive leap for pros.'
  },
  {
    id: 'm1-pro-14-16',
    name: 'MacBook Pro 14" (2021)',
    type: DeviceType.Laptop,
    chip: 'M1 Pro',
    family: ChipFamily.M1,
    cores_cpu: '10 (8P+2E)',
    cores_gpu: 16,
    memory: '16GB - 32GB',
    releaseYear: 2021,
    singleCoreScore: 2350,
    multiCoreScore: 12300,
    metalScore: 40000,
    basePriceUSD: 1999,
    description: 'Perhaps the most beloved modern MacBook Pro.'
  },
  {
    id: 'm1-imac',
    name: 'iMac 24" (2021)',
    type: DeviceType.Desktop,
    chip: 'M1',
    family: ChipFamily.M1,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 8,
    memory: '8GB - 16GB',
    releaseYear: 2021,
    singleCoreScore: 2320,
    multiCoreScore: 8400,
    metalScore: 21000,
    basePriceUSD: 1499,
    description: 'Ultra-thin colorful design.'
  },
  {
    id: 'm1-mini',
    name: 'Mac Mini (2020)',
    type: DeviceType.Desktop,
    chip: 'M1',
    family: ChipFamily.M1,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 8,
    memory: '8GB - 16GB',
    releaseYear: 2020,
    singleCoreScore: 2330,
    multiCoreScore: 8500,
    metalScore: 21500,
    basePriceUSD: 699,
    description: 'First desktop to get Apple Silicon.'
  },
  {
    id: 'm1-air',
    name: 'MacBook Air 13" (2020)',
    type: DeviceType.Laptop,
    chip: 'M1',
    family: ChipFamily.M1,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 7,
    memory: '8GB - 16GB',
    releaseYear: 2020,
    singleCoreScore: 2300,
    multiCoreScore: 8300,
    metalScore: 20000,
    basePriceUSD: 999,
    description: 'The legend that started the Apple Silicon revolution. Still viable for basic tasks.'
  },
  {
    id: 'm1-mbp-13',
    name: 'MacBook Pro 13" (2020)',
    type: DeviceType.Laptop,
    chip: 'M1',
    family: ChipFamily.M1,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 8,
    memory: '8GB - 16GB',
    releaseYear: 2020,
    singleCoreScore: 2310,
    multiCoreScore: 8400,
    metalScore: 21000,
    basePriceUSD: 1299,
    description: 'Same chassis as Intel, new heart.'
  },
  {
    id: 'ipad-pro-m1',
    name: 'iPad Pro 12.9" (M1)',
    type: DeviceType.Tablet,
    chip: 'M1',
    family: ChipFamily.M1,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 8,
    memory: '8GB - 16GB',
    releaseYear: 2021,
    singleCoreScore: 2300,
    multiCoreScore: 8400,
    metalScore: 32000,
    basePriceUSD: 1099,
    description: 'Mini-LED XDR display meets M1.'
  },
  {
    id: 'ipad-air-5-m1',
    name: 'iPad Air 5 (M1)',
    type: DeviceType.Tablet,
    chip: 'M1',
    family: ChipFamily.M1,
    cores_cpu: '8 (4P+4E)',
    cores_gpu: 8,
    memory: '8GB',
    releaseYear: 2022,
    singleCoreScore: 2280,
    multiCoreScore: 8300,
    metalScore: 30000,
    basePriceUSD: 599,
    description: 'Puts M1 power into the mainstream iPad chassis.'
  }
];